/* Auto-generated by genmsg_cpp for file /home/tesfamic/fuerte_workspace/sandbox/objectDetector0/msg/objectPos.msg */
#ifndef OBJECTDETECTOR0_MESSAGE_OBJECTPOS_H
#define OBJECTDETECTOR0_MESSAGE_OBJECTPOS_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace objectDetector0
{
template <class ContainerAllocator>
struct objectPos_ {
  typedef objectPos_<ContainerAllocator> Type;

  objectPos_()
  : width(0)
  , height(0)
  {
  }

  objectPos_(const ContainerAllocator& _alloc)
  : width(0)
  , height(0)
  {
  }

  typedef int16_t _width_type;
  int16_t width;

  typedef int16_t _height_type;
  int16_t height;


  typedef boost::shared_ptr< ::objectDetector0::objectPos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::objectDetector0::objectPos_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct objectPos
typedef  ::objectDetector0::objectPos_<std::allocator<void> > objectPos;

typedef boost::shared_ptr< ::objectDetector0::objectPos> objectPosPtr;
typedef boost::shared_ptr< ::objectDetector0::objectPos const> objectPosConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::objectDetector0::objectPos_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::objectDetector0::objectPos_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace objectDetector0

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::objectDetector0::objectPos_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::objectDetector0::objectPos_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::objectDetector0::objectPos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "5d7f0e302480e684afa7baf49b775bf2";
  }

  static const char* value(const  ::objectDetector0::objectPos_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x5d7f0e302480e684ULL;
  static const uint64_t static_value2 = 0xafa7baf49b775bf2ULL;
};

template<class ContainerAllocator>
struct DataType< ::objectDetector0::objectPos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "objectDetector0/objectPos";
  }

  static const char* value(const  ::objectDetector0::objectPos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::objectDetector0::objectPos_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int16 width\n\
int16 height\n\
\n\
";
  }

  static const char* value(const  ::objectDetector0::objectPos_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::objectDetector0::objectPos_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::objectDetector0::objectPos_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.width);
    stream.next(m.height);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct objectPos_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::objectDetector0::objectPos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::objectDetector0::objectPos_<ContainerAllocator> & v) 
  {
    s << indent << "width: ";
    Printer<int16_t>::stream(s, indent + "  ", v.width);
    s << indent << "height: ";
    Printer<int16_t>::stream(s, indent + "  ", v.height);
  }
};


} // namespace message_operations
} // namespace ros

#endif // OBJECTDETECTOR0_MESSAGE_OBJECTPOS_H

