/* Auto-generated by genmsg_cpp for file /home/tesfamic/fuerte_workspace/sandbox/objectLocation0/msg/coordinateContent.msg */
#ifndef OBJECTLOCATION0_MESSAGE_COORDINATECONTENT_H
#define OBJECTLOCATION0_MESSAGE_COORDINATECONTENT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace objectLocation0
{
template <class ContainerAllocator>
struct coordinateContent_ {
  typedef coordinateContent_<ContainerAllocator> Type;

  coordinateContent_()
  : x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  coordinateContent_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , z(0.0)
  {
  }

  typedef double _x_type;
  double x;

  typedef double _y_type;
  double y;

  typedef double _z_type;
  double z;


  typedef boost::shared_ptr< ::objectLocation0::coordinateContent_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::objectLocation0::coordinateContent_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct coordinateContent
typedef  ::objectLocation0::coordinateContent_<std::allocator<void> > coordinateContent;

typedef boost::shared_ptr< ::objectLocation0::coordinateContent> coordinateContentPtr;
typedef boost::shared_ptr< ::objectLocation0::coordinateContent const> coordinateContentConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::objectLocation0::coordinateContent_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::objectLocation0::coordinateContent_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace objectLocation0

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::objectLocation0::coordinateContent_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::objectLocation0::coordinateContent_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::objectLocation0::coordinateContent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "4a842b65f413084dc2b10fb484ea7f17";
  }

  static const char* value(const  ::objectLocation0::coordinateContent_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x4a842b65f413084dULL;
  static const uint64_t static_value2 = 0xc2b10fb484ea7f17ULL;
};

template<class ContainerAllocator>
struct DataType< ::objectLocation0::coordinateContent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "objectLocation0/coordinateContent";
  }

  static const char* value(const  ::objectLocation0::coordinateContent_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::objectLocation0::coordinateContent_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::objectLocation0::coordinateContent_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::objectLocation0::coordinateContent_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::objectLocation0::coordinateContent_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.z);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct coordinateContent_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::objectLocation0::coordinateContent_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::objectLocation0::coordinateContent_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<double>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<double>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<double>::stream(s, indent + "  ", v.z);
  }
};


} // namespace message_operations
} // namespace ros

#endif // OBJECTLOCATION0_MESSAGE_COORDINATECONTENT_H

